### ISSUE TITLE
Possible spam attack

### ISSUE THREAD

**Issue by dimiandre** [made-in-block/cw-drip#1]
https://github.com/made-in-block/cw-drip/blob/main/src/contract.rs#L227

It's not enough to check ` min_staking_amount` during stakers iteration. The only purpose of`min_staking_amount` is preventing spam attacks, therefore the check should also be implemented inside `execute_add_participant`. 

Stakers will send another "opt in" message if they start having the proper delegation. 

Additionally, a staker should be removed from list if during an iteration if we find he doesn't have the min stake anymore

**Comment by 0xstepit** [comment]
Ok nice, so I think is it better to just filter delegations higher than `min_staking_amount` instead of summing up all the delegations of a single account.

**Comment by dimiandre** [comment]
> Ok nice, so I think is it better to just filter delegations higher than `min_staking_amount` instead of summing up all the delegations of a single account.

yes
