### ISSUE TITLE
Allow creation of partial drip pools

### ISSUE THREAD

**Issue by dimiandre** [made-in-block/cw-drip#4]
maybe we can remove this check, so that community will be able to do multiple drip tranches one after the other without having to refill the contract every time

https://github.com/made-in-block/cw-drip/blob/main/src/contract.rs#L162

new check
```

    if available_amount < total_drip_amount {
        return Err(ContractError::WrongTokensAmount {
            tokens_amount: available_amount, 
            total_tokens: total_drip_amount
        })
    }
```

**Comment by 0xstepit** [comment]
This check is needed to avoid creating drip pool of more tokens than the available ones to the contract. Should we allow to create a drip pool of 1_000_000JUNO when the contract just own 1_000JUNO?

**Comment by dimiandre** [comment]
> This check is needed to avoid creating drip pool of more tokens than the available ones to the contract. Should we allow to create a drip pool of 1_000_000JUNO when the contract just own 1_000JUNO?

you can check that the drip pool is less than available amount instead of "same"

**Comment by 0xstepit** [comment]
It is 🤣

**Comment by 0xstepit** [comment]
The check is forcing to have at least the drip amount in the contract. The owner will be able to withdraw the remaining tokens after the distribution end
