### ISSUE TITLE
Calculation of next distribution time

### ISSUE THREAD

**Issue by dimiandre** [made-in-block/cw-drip#5]
https://github.com/made-in-block/cw-drip/blob/main/src/contract.rs#L248

Why not simply save `current block time + epoch duration` as next epoch?

**Comment by 0xstepit** [comment]
This is to take into account delay in the distribution. If the epoch finish at, let's say, block 10 but the distribution is triggered at block 12, the next distribution should be available at block 20, not 22.

**Comment by dimiandre** [comment]
I see, let's keep like this for now. No strong opinions from me

**Comment by 0xstepit** [comment]
Same for me. We can change it in 2 minutes
